/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JewelleriesRouteImport } from './routes/jewelleries'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMediaManagerRouteImport } from './routes/admin/media-manager'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminRatesRouteImport } from './routes/admin/rates'
import { Route as ApiAdminAuthRouteImport } from './routes/api/admin-auth'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiRatesRouteImport } from './routes/api/rates'
import { Route as JewelleriesIndexRouteImport } from './routes/jewelleries.index'
import { Route as JewelleriesSlugRouteImport } from './routes/jewelleries.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleriesRoute = JewelleriesRouteImport.update({
  id: '/jewelleries',
  path: '/jewelleries',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaManagerRoute = AdminMediaManagerRouteImport.update({
  id: '/media-manager',
  path: '/media-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRatesRoute = AdminRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminAuthRoute = ApiAdminAuthRouteImport.update({
  id: '/api/admin-auth',
  path: '/api/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRatesRoute = ApiRatesRouteImport.update({
  id: '/api/rates',
  path: '/api/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleriesIndexRoute = JewelleriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JewelleriesRoute,
} as any)
const JewelleriesSlugRoute = JewelleriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JewelleriesRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/jewelleries': typeof JewelleriesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media-manager': typeof AdminMediaManagerRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/rates': typeof AdminRatesRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/media': typeof ApiMediaRoute
  '/api/products': typeof ApiProductsRoute
  '/api/rates': typeof ApiRatesRoute
  '/jewelleries/$slug': typeof JewelleriesSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/jewelleries/': typeof JewelleriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media-manager': typeof AdminMediaManagerRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/rates': typeof AdminRatesRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/media': typeof ApiMediaRoute
  '/api/products': typeof ApiProductsRoute
  '/api/rates': typeof ApiRatesRoute
  '/jewelleries/$slug': typeof JewelleriesSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/jewelleries': typeof JewelleriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/jewelleries': typeof JewelleriesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media-manager': typeof AdminMediaManagerRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/rates': typeof AdminRatesRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/media': typeof ApiMediaRoute
  '/api/products': typeof ApiProductsRoute
  '/api/rates': typeof ApiRatesRoute
  '/jewelleries/$slug': typeof JewelleriesSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/jewelleries/': typeof JewelleriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/jewelleries'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/media-manager'
    | '/admin/products'
    | '/admin/rates'
    | '/api/admin-auth'
    | '/api/categories'
    | '/api/media'
    | '/api/products'
    | '/api/rates'
    | '/jewelleries/$slug'
    | '/product/$id'
    | '/admin/'
    | '/jewelleries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/media-manager'
    | '/admin/products'
    | '/admin/rates'
    | '/api/admin-auth'
    | '/api/categories'
    | '/api/media'
    | '/api/products'
    | '/api/rates'
    | '/jewelleries/$slug'
    | '/product/$id'
    | '/admin'
    | '/jewelleries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/jewelleries'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/media-manager'
    | '/admin/products'
    | '/admin/rates'
    | '/api/admin-auth'
    | '/api/categories'
    | '/api/media'
    | '/api/products'
    | '/api/rates'
    | '/jewelleries/$slug'
    | '/product/$id'
    | '/admin/'
    | '/jewelleries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  JewelleriesRoute: typeof JewelleriesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAdminAuthRoute: typeof ApiAdminAuthRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiProductsRoute: typeof ApiProductsRoute
  ApiRatesRoute: typeof ApiRatesRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewelleries': {
      id: '/jewelleries'
      path: '/jewelleries'
      fullPath: '/jewelleries'
      preLoaderRoute: typeof JewelleriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media-manager': {
      id: '/admin/media-manager'
      path: '/media-manager'
      fullPath: '/admin/media-manager'
      preLoaderRoute: typeof AdminMediaManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rates': {
      id: '/admin/rates'
      path: '/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AdminRatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin-auth': {
      id: '/api/admin-auth'
      path: '/api/admin-auth'
      fullPath: '/api/admin-auth'
      preLoaderRoute: typeof ApiAdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rates': {
      id: '/api/rates'
      path: '/api/rates'
      fullPath: '/api/rates'
      preLoaderRoute: typeof ApiRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewelleries/': {
      id: '/jewelleries/'
      path: '/'
      fullPath: '/jewelleries/'
      preLoaderRoute: typeof JewelleriesIndexRouteImport
      parentRoute: typeof JewelleriesRoute
    }
    '/jewelleries/$slug': {
      id: '/jewelleries/$slug'
      path: '/$slug'
      fullPath: '/jewelleries/$slug'
      preLoaderRoute: typeof JewelleriesSlugRouteImport
      parentRoute: typeof JewelleriesRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaManagerRoute: typeof AdminMediaManagerRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRatesRoute: typeof AdminRatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaManagerRoute: AdminMediaManagerRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRatesRoute: AdminRatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface JewelleriesRouteChildren {
  JewelleriesSlugRoute: typeof JewelleriesSlugRoute
  JewelleriesIndexRoute: typeof JewelleriesIndexRoute
}

const JewelleriesRouteChildren: JewelleriesRouteChildren = {
  JewelleriesSlugRoute: JewelleriesSlugRoute,
  JewelleriesIndexRoute: JewelleriesIndexRoute,
}

const JewelleriesRouteWithChildren = JewelleriesRoute._addFileChildren(
  JewelleriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  JewelleriesRoute: JewelleriesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAdminAuthRoute: ApiAdminAuthRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiRatesRoute: ApiRatesRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
